#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigationAdo.net
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="emp")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdept(dept instance);
    partial void Updatedept(dept instance);
    partial void Deletedept(dept instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::NavigationAdo.net.Properties.Settings.Default.empConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dept> depts
		{
			get
			{
				return this.GetTable<dept>();
			}
		}
		
		public System.Data.Linq.Table<emp> emps
		{
			get
			{
				return this.GetTable<emp>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dept")]
	public partial class dept : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _N_DEPT;
		
		private string _NOM;
		
		private string _LIEU;
		
		private System.Nullable<int> _n_employee;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnN_DEPTChanging(int value);
    partial void OnN_DEPTChanged();
    partial void OnNOMChanging(string value);
    partial void OnNOMChanged();
    partial void OnLIEUChanging(string value);
    partial void OnLIEUChanged();
    partial void Onn_employeeChanging(System.Nullable<int> value);
    partial void Onn_employeeChanged();
    #endregion
		
		public dept()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_DEPT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int N_DEPT
		{
			get
			{
				return this._N_DEPT;
			}
			set
			{
				if ((this._N_DEPT != value))
				{
					this.OnN_DEPTChanging(value);
					this.SendPropertyChanging();
					this._N_DEPT = value;
					this.SendPropertyChanged("N_DEPT");
					this.OnN_DEPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string NOM
		{
			get
			{
				return this._NOM;
			}
			set
			{
				if ((this._NOM != value))
				{
					this.OnNOMChanging(value);
					this.SendPropertyChanging();
					this._NOM = value;
					this.SendPropertyChanged("NOM");
					this.OnNOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIEU", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string LIEU
		{
			get
			{
				return this._LIEU;
			}
			set
			{
				if ((this._LIEU != value))
				{
					this.OnLIEUChanging(value);
					this.SendPropertyChanging();
					this._LIEU = value;
					this.SendPropertyChanged("LIEU");
					this.OnLIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n_employee", DbType="Int")]
		public System.Nullable<int> n_employee
		{
			get
			{
				return this._n_employee;
			}
			set
			{
				if ((this._n_employee != value))
				{
					this.Onn_employeeChanging(value);
					this.SendPropertyChanging();
					this._n_employee = value;
					this.SendPropertyChanged("n_employee");
					this.Onn_employeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.emp")]
	public partial class emp
	{
		
		private int _NUM;
		
		private string _NOM;
		
		private string _FONCTION;
		
		private System.Nullable<decimal> _N_SUP;
		
		private System.Nullable<System.DateTime> _EMBAUCHE;
		
		private System.Nullable<decimal> _SALAIRE;
		
		private System.Nullable<decimal> _comm;
		
		private System.Nullable<int> _N_DEPT;
		
		private string _tele;
		
		private string _email;
		
		private System.Nullable<int> _userid_;
		
		public emp()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM", DbType="Int NOT NULL")]
		public int NUM
		{
			get
			{
				return this._NUM;
			}
			set
			{
				if ((this._NUM != value))
				{
					this._NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string NOM
		{
			get
			{
				return this._NOM;
			}
			set
			{
				if ((this._NOM != value))
				{
					this._NOM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FONCTION", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string FONCTION
		{
			get
			{
				return this._FONCTION;
			}
			set
			{
				if ((this._FONCTION != value))
				{
					this._FONCTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_SUP", DbType="Decimal(4,0)")]
		public System.Nullable<decimal> N_SUP
		{
			get
			{
				return this._N_SUP;
			}
			set
			{
				if ((this._N_SUP != value))
				{
					this._N_SUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMBAUCHE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EMBAUCHE
		{
			get
			{
				return this._EMBAUCHE;
			}
			set
			{
				if ((this._EMBAUCHE != value))
				{
					this._EMBAUCHE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALAIRE", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> SALAIRE
		{
			get
			{
				return this._SALAIRE;
			}
			set
			{
				if ((this._SALAIRE != value))
				{
					this._SALAIRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comm", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> comm
		{
			get
			{
				return this._comm;
			}
			set
			{
				if ((this._comm != value))
				{
					this._comm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_DEPT", DbType="Int")]
		public System.Nullable<int> N_DEPT
		{
			get
			{
				return this._N_DEPT;
			}
			set
			{
				if ((this._N_DEPT != value))
				{
					this._N_DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tele", DbType="VarChar(90)")]
		public string tele
		{
			get
			{
				return this._tele;
			}
			set
			{
				if ((this._tele != value))
				{
					this._tele = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(89)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="userid#", Storage="_userid_", DbType="Int")]
		public System.Nullable<int> userid_
		{
			get
			{
				return this._userid_;
			}
			set
			{
				if ((this._userid_ != value))
				{
					this._userid_ = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
